name: crop_disease_detection
description: A Flutter app for crop disease detection.

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  image_picker: ^1.1.2
  file_selector: ^1.0.3
  camera: ^0.11.0+2
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  firebase_auth_web: ^5.9.0
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.0
  shimmer: ^3.0.0  
  path_provider: ^2.0.13
  tflite_flutter: ^0.11.0
flutter:
  uses-material-design: true
  assets:
    - assets/Logo.png
    - assets/graphic_image.png
    - assets/healthcheck.png
    - assets/community.png
    - assets/cultivationtips.png
    - assets/tomato2.png
    - assets/potato2.png
    - assets/pepper.png
    - assets/lemon.png
    - assets/rice.png
    - assets/corn.png
    - assets/onion.jpg
    - assets/wheat.png
    - assets/carrot.png
    - assets/cabbage.png
    - assets/crop_disease_model.tflite
    - assets/data/labels_with_symptoms.json

dev_dependencies:
  flutter_launcher_icons: ^0.14.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Logo.png"

