// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvejM9EKEaB5y0EDygp5itIqrcg5Pf0pw',
    appId: '1:739238588953:web:2a3b72e0e4aed6d13f7088',
    messagingSenderId: '739238588953',
    projectId: 'cropfit-da2fb',
    authDomain: 'cropfit-da2fb.firebaseapp.com',
    storageBucket: 'cropfit-da2fb.firebasestorage.app',
    measurementId: 'G-5ZWH9JV08E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZgW5F1ysigDEyL7Nu9RdsQc4lqheoCL0',
    appId: '1:739238588953:android:badb2a7b5f0899cb3f7088',
    messagingSenderId: '739238588953',
    projectId: 'cropfit-da2fb',
    storageBucket: 'cropfit-da2fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTebS41_TUu7MvUPBz7C2dqKrLr3gMGR0',
    appId: '1:739238588953:ios:ba20fb7ea676cea33f7088',
    messagingSenderId: '739238588953',
    projectId: 'cropfit-da2fb',
    storageBucket: 'cropfit-da2fb.firebasestorage.app',
    iosBundleId: 'com.example.cropDiseaseDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTebS41_TUu7MvUPBz7C2dqKrLr3gMGR0',
    appId: '1:739238588953:ios:ba20fb7ea676cea33f7088',
    messagingSenderId: '739238588953',
    projectId: 'cropfit-da2fb',
    storageBucket: 'cropfit-da2fb.firebasestorage.app',
    iosBundleId: 'com.example.cropDiseaseDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvejM9EKEaB5y0EDygp5itIqrcg5Pf0pw',
    appId: '1:739238588953:web:bb31064adcef3ad23f7088',
    messagingSenderId: '739238588953',
    projectId: 'cropfit-da2fb',
    authDomain: 'cropfit-da2fb.firebaseapp.com',
    storageBucket: 'cropfit-da2fb.firebasestorage.app',
    measurementId: 'G-NYJQR3GSFR',
  );

}